# Generated by Django 5.2.7 on 2025-10-07 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter the first name of the author', max_length=100, verbose_name='Name of Author')),
                ('last_name', models.CharField(help_text='Enter the last name of the author', max_length=100, verbose_name='Family Name of Author')),
                ('date_of_birth', models.DateField(blank=True, help_text='Enter the date of birth of the author', null=True, verbose_name='Date of Birth')),
                ('date_of_death', models.DateField(blank=True, help_text='Enter the date of death of the author', null=True, verbose_name='Date of Death')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the genre of the book', max_length=200, verbose_name='Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the language of the book', max_length=20, verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the status of the book', max_length=20, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the book', max_length=200, verbose_name='Title')),
                ('summary', models.TextField(help_text='Enter the summary of the book', max_length=1000, verbose_name='Summary')),
                ('isnb', models.CharField(help_text='Enter the ISBN of the book', max_length=13, verbose_name='ISBN')),
                ('author', models.ManyToManyField(help_text='Enter the author of the book', null=True, to='catalog.author', verbose_name='Author')),
                ('genre', models.ForeignKey(help_text='Enter the genre of the book', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.genre', verbose_name='Genre')),
                ('language', models.ForeignKey(help_text='Enter the language of the book', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.language', verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_nom', models.CharField(help_text='Enter the inverter number of the book', max_length=20, null=True, verbose_name='Inverter Number')),
                ('imprint', models.CharField(help_text='Enter the publisher and year of publication', max_length=200, verbose_name='Publisher')),
                ('due_back', models.DateField(blank=True, help_text='Enter the due date of the book', null=True, verbose_name='Due Date')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
                ('status', models.ForeignKey(help_text='Changing instance status', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.status', verbose_name='Status')),
            ],
        ),
    ]
