# Generated by Django 5.2.7 on 2025-10-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='Enter the author of the book', to='catalog.author', verbose_name='Author'),
        ),
    ]
